Our Funding
The Malawi Academy for Sports is funded through a combination of government support, private partnerships, and community contributions. Our funding sources include:
Government Grants – Support from the Malawi National Council of Sports to develop youth sports programs.
Corporate Sponsorships – Partnerships with local and international businesses that help sponsor training programs, equipment, and facilities.
Community Contributions – Donations from individuals and community groups who support the development of young athletes.
Project-Based Funding – Specific grants or donations targeted at particular sports programs or events.
These funds ensure that our athletes receive quality training, access to sports facilities, and opportunities to represent Malawi nationally and internationally
